//! `repowise generate-claude-md` -- write a managed block of codebase
//! intelligence into `CLAUDE.md`/`AGENTS.md`, preserving everything
//! around it.
//!
//! # The marker discipline is the feature
//!
//! This writes into a file a human also edits. The content it generates
//! is derived and cheap to reproduce; the prose someone wrote by hand
//! around it is neither. So the invariant is absolute: **a regeneration
//! must never be able to eat hand-written content.**
//!
//! `hook.rs` already has exactly this pattern working -- `HOOK_MARKER`
//! is what authorizes overwriting a hook, and a hook without it is
//! treated as foreign and refused. The same rule applies here:
//!
//! - No markers in an existing file -> **append** a block. Never rewrite
//!   the document.
//! - Both markers present -> replace only what's between them.
//! - Markers malformed (an opener with no closer, or a closer before its
//!   opener) -> **refuse**. Something truncated or reordered the file,
//!   and guessing where the block ends is exactly how prose gets eaten.

use repowise_core::RepoIndex;
use repowise_graph::RepoGraph;
use std::path::Path;

pub const BEGIN_MARKER: &str = "<!-- BEGIN repowise -- generated, do not edit inside -->";
pub const END_MARKER: &str = "<!-- END repowise -->";

/// Where the managed block goes by default.
///
/// `.claude/CLAUDE.md`, matching the reference -- deliberately **not**
/// a repo-root `CLAUDE.md`, which in this very repo is a hand-written
/// governance file. Defaulting to overwrite-adjacent behavior on that
/// would be an unpleasant surprise.
pub const DEFAULT_OUTPUT: &str = ".claude/CLAUDE.md";

/// Where `generate-agents-md` writes by default (issue #333).
///
/// A repo-root `AGENTS.md`, which is the cross-agent convention Codex
/// and opencode read -- unlike `CLAUDE.md`, it has no established
/// hand-written meaning in this repo, so a root default is safe here in
/// a way it isn't for `CLAUDE.md`. The managed-marker rules are
/// identical either way: prose outside the markers is never touched.
pub const AGENTS_OUTPUT: &str = "AGENTS.md";

/// What we found in the target file's *content*.
///
/// Deliberately has no "no file" variant: file absence is settled by
/// `splice` before this is ever called, so this enum describes text and
/// nothing else.
#[derive(Debug, PartialEq, Eq)]
pub enum BlockState {
    /// Content with no repowise markers. Someone else's document: we
    /// append, never rewrite.
    NoMarkers,
    /// Both markers, in order. Ours to replace.
    Managed { start: usize, end: usize },
    /// Markers present but unusable. Refused rather than guessed at.
    Malformed(&'static str),
}

/// Locate the managed block in `content`.
pub fn find_block(content: &str) -> BlockState {
    let begin = content.find(BEGIN_MARKER);
    let end = content.find(END_MARKER);
    match (begin, end) {
        (None, None) => BlockState::NoMarkers,
        (Some(_), None) => BlockState::Malformed(
            "found the repowise BEGIN marker with no matching END marker -- the file \
             looks truncated. Refusing to guess where the managed block ends; fix or \
             remove the stray marker and re-run.",
        ),
        (None, Some(_)) => BlockState::Malformed(
            "found the repowise END marker with no matching BEGIN marker. Refusing to \
             guess where the managed block starts; fix or remove the stray marker and \
             re-run.",
        ),
        (Some(b), Some(e)) if e < b => BlockState::Malformed(
            "the repowise END marker appears before its BEGIN marker. Refusing to touch \
             a file whose managed block is inverted.",
        ),
        (Some(b), Some(e)) => BlockState::Managed {
            start: b,
            end: e + END_MARKER.len(),
        },
    }
}

/// Render the managed block's body from the index.
///
/// Everything here is already computed by another command; this is a
/// presentation of it, not a new analysis.
/// Render the managed block.
///
/// `generator` is the command that produces it, named in the block's own
/// preamble so a reader can regenerate it. Parameterized because the
/// same block backs both `CLAUDE.md` and `AGENTS.md` -- a block in
/// `AGENTS.md` telling a Codex or opencode user to run
/// `generate-claude-md` would send them to the wrong file (issue #333).
pub fn render_block(index: &RepoIndex, graph: &RepoGraph, root: &Path, generator: &str) -> String {
    let overview = graph.overview(index);
    let health = repowise_health::analyze(index, graph);

    let mut out = String::new();
    out.push_str(BEGIN_MARKER);
    out.push_str("\n\n## Codebase intelligence\n\n");
    out.push_str(&format!(
        "Generated by `repowise {generator}` from the index. Edits inside this\n\
         block are overwritten on the next run; write anything you want to keep\n\
         outside the markers.\n\n"
    ));

    out.push_str(&format!(
        "- **{} indexed file(s)**, {} total line(s), {} symbol(s).\n",
        overview.file_count,
        overview.total_lines,
        index.files.iter().map(|f| f.symbols.len()).sum::<usize>()
    ));

    let mut langs: Vec<(String, usize)> = overview.by_language.clone();
    langs.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));
    if !langs.is_empty() {
        let listed: Vec<String> = langs
            .iter()
            .take(5)
            .map(|(lang, n)| format!("{lang} ({n})"))
            .collect();
        out.push_str(&format!("- **Languages:** {}\n", listed.join(", ")));
    }

    if let Some(commit) = &index.indexed_commit {
        out.push_str(&format!("- **Indexed at commit:** `{commit}`\n"));
    } else {
        // Same rule as the MCP `_meta` block: unknown is stated, not
        // quietly omitted so the block looks authoritative.
        out.push_str(
            "- **Indexed at commit:** unknown (no git, or an index predating commit stamping)\n",
        );
    }

    if !overview.most_depended_on.is_empty() {
        out.push_str("\n### Most depended-on files\n\n");
        out.push_str("Changing these reaches furthest.\n\n");
        for (file, count) in overview.most_depended_on.iter().take(8) {
            out.push_str(&format!(
                "- `{}` -- {count} dependent(s)\n",
                display_rel(file, root)
            ));
        }
    }

    if !health.file_scores.is_empty() {
        out.push_str("\n### Lowest health scores\n\n");
        out.push_str(&format!(
            "Deterministic markers, 0-10 (higher is better). Repo average {:.1}.\n\n",
            health.average_score
        ));
        for fh in health.file_scores.iter().take(8) {
            out.push_str(&format!(
                "- `{}` -- {:.1} ({} finding(s))\n",
                display_rel(&fh.file, root),
                fh.score,
                fh.finding_count
            ));
        }
    }

    let decisions = repowise_adr::mine(index).unwrap_or_default();
    if !decisions.is_empty() {
        out.push_str("\n### Architectural decisions\n\n");
        for d in decisions.iter().take(8) {
            out.push_str(&format!("- {}\n", d.title));
        }
        if decisions.len() > 8 {
            out.push_str(&format!(
                "- ... {} more (`repowise decisions`)\n",
                decisions.len() - 8
            ));
        }
    }

    out.push_str(&format!(
        "\nRun `repowise update` to refresh the index, then re-run this command.\n\n{END_MARKER}"
    ));
    out
}

fn display_rel(path: &Path, root: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .display()
        .to_string()
        .replace('\\', "/")
}

/// Splice `block` into `existing`, per the marker rules in the module
/// doc. Returns the new full file content.
pub fn splice(existing: Option<&str>, block: &str) -> Result<(String, WriteAction), String> {
    let Some(existing) = existing else {
        return Ok((format!("{block}\n"), WriteAction::Created));
    };
    match find_block(existing) {
        BlockState::Malformed(why) => Err(why.to_string()),
        BlockState::NoMarkers => {
            // Append. The existing document is someone else's and is
            // never rewritten -- only added to.
            let sep = if existing.ends_with("\n\n") {
                ""
            } else if existing.ends_with('\n') {
                "\n"
            } else {
                "\n\n"
            };
            Ok((format!("{existing}{sep}{block}\n"), WriteAction::Appended))
        }
        BlockState::Managed { start, end } => Ok((
            format!("{}{}{}", &existing[..start], block, &existing[end..]),
            WriteAction::Replaced,
        )),
    }
}

#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum WriteAction {
    Created,
    Appended,
    Replaced,
}

impl WriteAction {
    pub fn label(&self) -> &'static str {
        match self {
            WriteAction::Created => "created",
            WriteAction::Appended => "appended a managed block to",
            WriteAction::Replaced => "updated the managed block in",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const BLOCK: &str =
        "<!-- BEGIN repowise -- generated, do not edit inside -->\nBODY\n<!-- END repowise -->";

    /// `CLAUDE.md` and `AGENTS.md` must carry the *same* intelligence,
    /// differing only in the command each tells you to re-run (issue
    /// #333). Asserted by diffing two real renders rather than by
    /// eyeballing, so the two can't quietly drift apart as the block
    /// grows.
    #[test]
    fn both_generators_render_the_same_block_apart_from_their_own_name() {
        // `std::env::temp_dir`, matching this crate's other tests --
        // repowise-cli carries no `tempfile` dev-dependency.
        let root = std::env::temp_dir().join("repowise-agent-md-parity");
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        let root = root.canonicalize().unwrap();
        std::fs::write(root.join("a.rs"), "pub fn a() -> i32 { 1 }\n").unwrap();
        let index = repowise_parser::build_index(&root).unwrap();
        let graph = RepoGraph::build(&index);

        let claude = render_block(&index, &graph, &root, "generate-claude-md");
        let agents = render_block(&index, &graph, &root, "generate-agents-md");

        assert!(claude.contains("`repowise generate-claude-md`"));
        assert!(agents.contains("`repowise generate-agents-md`"));
        assert!(
            !agents.contains("generate-claude-md"),
            "an AGENTS.md block must not send a Codex/opencode user to the Claude Code command"
        );
        assert_eq!(
            claude.replace("generate-claude-md", "X"),
            agents.replace("generate-agents-md", "X"),
            "the two blocks must differ only in the command they name"
        );
    }

    #[test]
    fn a_missing_file_is_created() {
        let (out, action) = splice(None, BLOCK).unwrap();
        assert_eq!(action, WriteAction::Created);
        assert!(out.contains("BODY"));
    }

    /// The invariant this whole module exists for: a file with no
    /// markers belongs to someone else, and must only ever be added to.
    #[test]
    fn an_unmarked_file_is_appended_to_never_rewritten() {
        let existing = "# My notes\n\nHand-written guidance that must survive.\n";
        let (out, action) = splice(Some(existing), BLOCK).unwrap();
        assert_eq!(action, WriteAction::Appended);
        assert!(
            out.starts_with("# My notes"),
            "the original document must be intact and first:\n{out}"
        );
        assert!(out.contains("Hand-written guidance that must survive."));
        assert!(out.contains("BODY"));
    }

    #[test]
    fn a_managed_block_is_replaced_and_surrounding_prose_survives() {
        let existing = format!(
            "# Top matter\n\n{BEGIN_MARKER}\nOLD CONTENT\n{END_MARKER}\n\n## Tail matter\nkeep me\n"
        );
        let (out, action) = splice(Some(&existing), BLOCK).unwrap();
        assert_eq!(action, WriteAction::Replaced);
        assert!(!out.contains("OLD CONTENT"), "{out}");
        assert!(out.contains("BODY"), "{out}");
        assert!(
            out.contains("# Top matter"),
            "prose above must survive:\n{out}"
        );
        assert!(out.contains("keep me"), "prose below must survive:\n{out}");
    }

    #[test]
    fn regenerating_twice_is_stable() {
        let existing = format!("# Doc\n\n{BEGIN_MARKER}\nOLD\n{END_MARKER}\n");
        let (once, _) = splice(Some(&existing), BLOCK).unwrap();
        let (twice, action) = splice(Some(&once), BLOCK).unwrap();
        assert_eq!(action, WriteAction::Replaced);
        assert_eq!(once, twice, "a second run must be a no-op, not an append");
        assert_eq!(
            twice.matches(BEGIN_MARKER).count(),
            1,
            "markers must not accumulate:\n{twice}"
        );
    }

    /// Refusing is the whole point. An opener with no closer means
    /// something truncated the file, and guessing where the block ends
    /// is precisely how hand-written prose gets eaten.
    #[test]
    fn a_truncated_block_is_refused_not_guessed_at() {
        let existing = format!("# Doc\n\n{BEGIN_MARKER}\nhalf a block and then nothing\n");
        let err = splice(Some(&existing), BLOCK).unwrap_err();
        assert!(err.contains("truncated"), "{err}");
        assert!(err.contains("Refusing"), "{err}");
    }

    #[test]
    fn a_stray_end_marker_is_refused() {
        let existing = format!("# Doc\n\n{END_MARKER}\n");
        let err = splice(Some(&existing), BLOCK).unwrap_err();
        assert!(err.contains("no matching BEGIN"), "{err}");
    }

    #[test]
    fn an_inverted_block_is_refused() {
        let existing = format!("{END_MARKER}\nstuff\n{BEGIN_MARKER}\n");
        let err = splice(Some(&existing), BLOCK).unwrap_err();
        assert!(err.contains("inverted"), "{err}");
    }

    #[test]
    fn find_block_reports_no_markers_for_plain_prose() {
        assert_eq!(find_block("just some text\n"), BlockState::NoMarkers);
    }
}
