[package]
name = "repowise-workspace"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
repowise-core = { path = "../repowise-core" }
repowise-git = { path = "../repowise-git" }
repowise-graph = { path = "../repowise-graph" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
toml = "0.8"
regex = "1"

[dev-dependencies]
tempfile = "3"
repowise-parser = { path = "../repowise-parser" }
